services:
  mnxo-uoapp-backend-db-playground:
    hostname: localhost
    image: mongo:7.0.11
    container_name: ${DATABASE_NAME}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_EXTERNAL_PORT}:${DATABASE_INTERNAL_PORT}'
    volumes:
      - ./${DATABASE_NAME}:/data/db
  mnxo-uoapp-backend-redis-db-playground:
    container_name: mnxo-uoapp-backend-redis-db-playground
    image: redis:7
    ports:
      - '${REDIS_EXTERNAL_PORT}:${REDIS_INTERNAL_PORT}'
    volumes:
      - ./mnxo-uoapp-backend-redis-db-playground:/data
volumes:
  mnxo-uoapp-backend-redis-db-playground:
  mnxo-uoapp-backend-db-playground: #TODO: Add everything related to Healthcheck.
