services:
  mnxo-uoapp-backend-db-pre-prod:
    hostname: mnxo-uoapp-backend-db-pre-prod
    image: mongo:7.0.11
    restart: always
    env_file:
      - .pre-production.env
    container_name: ${DATABASE_NAME}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_EXTERNAL_PORT}:${DATABASE_INTERNAL_PORT}'

    volumes:
      - ./${DATABASE_NAME}:/data/db
    networks:
      mnxo-uoapp-network:
        ipv4_address: 173.168.24.11
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet mongodb://localhost:27017/test || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  mnxo-uoapp-redis-db-pre-prod:
    hostname: mnxo-uoapp-redis-db-pre-prod
    container_name: mnxo-uoapp-redis-db-pre-prod
    image: redis:7
    ports:
      - '${REDIS_EXTERNAL_PORT}:${REDIS_INTERNAL_PORT}'
    volumes:
      - ./mnxo-uoapp-redis-db-pre-prod:/data
    networks:
      mnxo-uoapp-network:
        ipv4_address: 173.168.24.12
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3

  mnxo-uoapp-backend:
    container_name: mnxo-uoapp-backend
    env_file:
      - .pre-production.env
    image: mnxo-uoapp-backend:${TAG}
    ports:
      - '${PORT}:${PORT}'
    restart: always
    depends_on:
      mnxo-uoapp-backend-db-pre-prod:
        condition: service_healthy
      mnxo-uoapp-redis-db-pre-prod:
        condition: service_started # Redis no tiene healthcheck, solo espera a que inicie
    networks:
      mnxo-uoapp-network:
        ipv4_address: 173.168.24.13
 
volumes:
  mnxo-uoapp-redis-db-pre-prod:
  mnxo-uoapp-backend-db-pre-prod:
networks:
  mnxo-uoapp-network:
    name: mnxo-uoapp-backend-network
    driver: bridge
    ipam:
      config:
        - subnet: 173.168.24.0/24
