import { registerAs } from '@nestjs/config';

export default registerAs('platform', () => ({
  OWN_PLATFORM_BASE_URL: process.env.OWN_PLATFORM_BASE_URL,
  OWN_PLATFORM_ALIAS: process.env.OWN_PLATFORM_ALIAS,
  OWN_PLATFORM_CLIENT_ID: process.env.OWN_PLATFORM_CLIENT_ID,
  OWN_PLATFORM_CLIENT_SECRET: process.env.OWN_PLATFORM_CLIENT_SECRET,
  OWN_PLATFORM_KEYCLOAK_ID: process.env.OWN_PLATFORM_KEYCLOAK_ID,
  FRONTEND_CLIENT_BASE_URL: process.env.FRONTEND_CLIENT_BASE_URL,
  FRONTEND_CLIENT_KEYCLOAK_ID: process.env.FRONTEND_CLIENT_KEYCLOAK_ID,
  FRONTEND_CLIENT_EMAIL: process.env.FRONTEND_CLIENT_EMAIL,
  FRONTEND_CLIENT_FORGOT_URL: process.env.FRONTEND_CLIENT_FORGOT_URL,
  FRONTEND_CLIENT_ID: process.env.FRONTEND_CLIENT_ID,
  FRONTEND_CLIENT_SECRET: process.env.FRONTEND_CLIENT_SECRET,
}));
