export enum AlsKeysEnum {
  APP_USER = 'APP_USER',
  START_TIME = 'START_TIME',
  URL = 'URL',
  IP = 'IP',
  CLIENT = 'CLIENT',
  DEFAULT_LANGUAGE = 'DEFAULT_LANGUAGE',
  PAGINATION_PARAMS = 'PAGINATION_PARAMS',
  FILTER_OPTIONS = 'FILTER_OPTIONS',
  LANGUAGE = 'LANGUAGE',
}
