export enum ExamAttemptStatusEnum {
  CREATED = 'CREATED',
  APPROVED = 'APPROVED',
  FINISHED = 'FINISHED',
  IN_PROCESS = 'IN_PROCESS',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  PENDING = 'PENDING',
  GRADED = 'GRADED',
  FAILED = 'FAILED',
  ABANDONED = 'ABANDONED',
  NOT_STARTED = 'NOT_STARTED',
}
