export enum ModerationStatusAliasEnum {
  MODERATION_APPROVED = 'MODERATION_APPROVED',
  MODERATION_PENDING = 'MODERATION_PENDING',
  MODERATION_REJECTED = 'MODERATION_REJECTED',
  MODERATION_EMAIL_RESENT = 'MODERATION_EMAIL_RESENT',
  USER_ACTIVATED = 'USER_ACTIVATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
}
