export const RequiredUserActionsEnum = {
  VERIFY_EMAIL: 'VERIFY_EMAIL',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  CONFIGURE_TOTP: 'CONFIGURE_TOTP',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  UPDATE_EMAIL: 'UPDATE_EMAIL',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT',
};
